# coding: utf-8

"""
    Arcane Engine API

    API for creating Arcane Engine tasks

    The version of the OpenAPI document: 1.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arcane.models.pr_number_response import PRNumberResponse

class TestPRNumberResponse(unittest.TestCase):
    """PRNumberResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PRNumberResponse:
        """Test PRNumberResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PRNumberResponse`
        """
        model = PRNumberResponse()
        if include_optional:
            return PRNumberResponse(
                pr_number = 56
            )
        else:
            return PRNumberResponse(
                pr_number = 56,
        )
        """

    def testPRNumberResponse(self):
        """Test PRNumberResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
