# coding: utf-8

"""
    Arcane Engine API

    API for creating Arcane Engine tasks

    The version of the OpenAPI document: 1.13.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arcane.api.repository_installation_api import RepositoryInstallationApi


class TestRepositoryInstallationApi(unittest.TestCase):
    """RepositoryInstallationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RepositoryInstallationApi()

    def tearDown(self) -> None:
        pass

    def test_repositories_installation_status_retrieve(self) -> None:
        """Test case for repositories_installation_status_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
