# coding: utf-8

"""
    Arcane Engine API

    API for creating Arcane Engine tasks

    The version of the OpenAPI document: 1.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arcane.api.pr_retrieval_api import PRRetrievalApi


class TestPRRetrievalApi(unittest.TestCase):
    """PRRetrievalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PRRetrievalApi()

    def tearDown(self) -> None:
        pass

    def test_resolve_pr_create(self) -> None:
        """Test case for resolve_pr_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
