# coding: utf-8

"""
    Arcane Engine API

    API for creating Arcane Engine tasks

    The version of the OpenAPI document: 1.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from arcane.api.task_creation_api import TaskCreationApi


class TestTaskCreationApi(unittest.TestCase):
    """TaskCreationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskCreationApi()

    def tearDown(self) -> None:
        pass

    def test_tasks_create(self) -> None:
        """Test case for tasks_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
